#!/usr/bin/env python3
"""
Script to generate the HTML site for GitHub Pages.
This script uses the explore() function from pandas_nhanes to generate 
an interactive HTML table of NHANES variables.
"""

import os
import sys
import pandas as pd
import itables
from itables import to_html_datatable

# Add the package to Python path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from pandas_nhanes.api import get_variables

def generate_site():
    """Generate the HTML site for GitHub Pages"""
    
    # Create site directory
    site_dir = 'site'
    os.makedirs(site_dir, exist_ok=True)
    
    # Get variables DataFrame
    print("Loading NHANES variables...")
    df = get_variables()
    print(f"Loaded {len(df)} variables from {df['dataset'].nunique()} datasets")
    
    # Configure itables for better rendering
    itables.options.maxBytes = 0
    itables.options.lengthMenu = [10, 25, 50, 100, 500, 1000]
    itables.options.pageLength = 25
    
    # Generate the main HTML page
    print("Generating interactive HTML table...")
    html_content = to_html_datatable(df, 
                                   table_id="nhanes-variables",
                                   showIndex=False,
                                   classes="display compact")
    
    # Create a complete HTML page with proper structure
    full_html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NHANES Variables Explorer</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f8f9fa;
        }}
        .header {{
            text-align: center;
            margin-bottom: 30px;
            padding: 20px;
            background: white;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        .header h1 {{
            color: #2c3e50;
            margin: 0 0 10px 0;
        }}
        .header p {{
            color: #666;
            margin: 5px 0;
        }}
        .stats {{
            display: flex;
            justify-content: center;
            gap: 30px;
            margin: 15px 0;
        }}
        .stat {{
            text-align: center;
        }}
        .stat-number {{
            font-size: 24px;
            font-weight: bold;
            color: #3498db;
        }}
        .stat-label {{
            font-size: 14px;
            color: #666;
        }}
        .table-container {{
            background: white;
            border-radius: 8px;
            padding: 20px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        .footer {{
            text-align: center;
            margin-top: 30px;
            padding: 20px;
            background: white;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            color: #666;
        }}
        .footer a {{
            color: #3498db;
            text-decoration: none;
        }}
        .footer a:hover {{
            text-decoration: underline;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>NHANES Variables Explorer</h1>
        <p>Interactive table of all available NHANES (National Health and Nutrition Examination Survey) variables</p>
        <div class="stats">
            <div class="stat">
                <div class="stat-number">{len(df):,}</div>
                <div class="stat-label">Variables</div>
            </div>
            <div class="stat">
                <div class="stat-number">{df['dataset'].nunique():,}</div>
                <div class="stat-label">Datasets</div>
            </div>
            <div class="stat">
                <div class="stat-number">{df['cycle name'].nunique():,}</div>
                <div class="stat-label">Survey Cycles</div>
            </div>
        </div>
    </div>
    
    <div class="table-container">
        {html_content}
    </div>
    
    <div class="footer">
        <p>Generated by <a href="https://github.com/jeromevde/Pandas-Nhanes">pandas-nhanes</a></p>
        <p>Data source: <a href="https://www.cdc.gov/nchs/nhanes/">CDC NHANES</a></p>
    </div>
</body>
</html>
"""
    
    # Write the HTML file
    html_path = os.path.join(site_dir, 'index.html')
    with open(html_path, 'w', encoding='utf-8') as f:
        f.write(full_html)
    
    print(f"Site generated successfully at: {html_path}")
    print(f"Total file size: {os.path.getsize(html_path) / 1024:.1f} KB")

if __name__ == "__main__":
    generate_site()
